__author__ = "spiceworm"
__author_email__ = "me@spiceworm.xyz"
__description__ = "Python blockchain"
__license__ = "Apache 2.0"
__title__ = "pychain"
__url__ = f"https://github.com/spiceworm/{__title__}"
__version__ = "0.1.0"
